# Generated by Django 2.0.4 on 2018-04-17 01:53

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('koin_id', models.AutoField(primary_key=True, serialize=False)),
                ('koin_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kur',
            fields=[
                ('kur_id', models.AutoField(primary_key=True, serialize=False)),
                ('kur_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.DecimalField(decimal_places=10, default=Decimal('0E-10'), max_digits=20)),
                ('high', models.DecimalField(decimal_places=10, default=Decimal('0E-10'), max_digits=20)),
                ('low', models.DecimalField(decimal_places=10, default=Decimal('0E-10'), max_digits=20)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('base_volume', models.DecimalField(decimal_places=10, default=Decimal('0E-10'), max_digits=20)),
                ('volume', models.DecimalField(decimal_places=10, default=Decimal('0E-10'), max_digits=20)),
                ('change', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('koin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation_app.Coin')),
                ('kur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation_app.Kur')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('koin_id', 'kur_id', 'time')},
        ),
    ]
