# Generated by Django 2.0.4 on 2018-04-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
    ]
