# Generated by Django 2.0.4 on 2018-04-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_app', '0002_auto_20180417_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=20, null=True),
        ),
    ]
